=begin
#Optimizers API

#Unified API for multiple optimizer engines dedicated to Vehicle Routing Problems

OpenAPI spec version: 0.1.0
Contact: tech@mapotempo.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

module OptimizerClient
  VERSION = '1.0.0'
end
