=begin
#Optimizers API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.1.0
Contact: tech@mapotempo.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

# Common files
require 'optimizer-client/api_client'
require 'optimizer-client/api_error'
require 'optimizer-client/version'
require 'optimizer-client/configuration'

# Models
require 'optimizer-client/models/post01_vrp_submit'
require 'optimizer-client/models/post01_vrp_submit_configuration'
require 'optimizer-client/models/post01_vrp_submit_points'
require 'optimizer-client/models/post01_vrp_submit_services'
require 'optimizer-client/models/post01_vrp_submit_shipments'
require 'optimizer-client/models/post01_vrp_submit_timewindows'
require 'optimizer-client/models/post01_vrp_submit_vehicles'
require 'optimizer-client/models/post01_vrp_submit_vrp'
require 'optimizer-client/models/post01_vrp_submit_vrp_activity'
require 'optimizer-client/models/post01_vrp_submit_vrp_capacities'
require 'optimizer-client/models/post01_vrp_submit_vrp_configuration'
require 'optimizer-client/models/post01_vrp_submit_vrp_configuration_preprocessing'
require 'optimizer-client/models/post01_vrp_submit_vrp_configuration_preprocessing_partitions'
require 'optimizer-client/models/post01_vrp_submit_vrp_configuration_resolution'
require 'optimizer-client/models/post01_vrp_submit_vrp_configuration_restitution'
require 'optimizer-client/models/post01_vrp_submit_vrp_configuration_schedule'
require 'optimizer-client/models/post01_vrp_submit_vrp_configuration_schedule_range_date'
require 'optimizer-client/models/post01_vrp_submit_vrp_configuration_schedule_range_indices'
require 'optimizer-client/models/post01_vrp_submit_vrp_location'
require 'optimizer-client/models/post01_vrp_submit_vrp_matrices'
require 'optimizer-client/models/post01_vrp_submit_vrp_points'
require 'optimizer-client/models/post01_vrp_submit_vrp_quantities'
require 'optimizer-client/models/post01_vrp_submit_vrp_relations'
require 'optimizer-client/models/post01_vrp_submit_vrp_rests'
require 'optimizer-client/models/post01_vrp_submit_vrp_routes'
require 'optimizer-client/models/post01_vrp_submit_vrp_services'
require 'optimizer-client/models/post01_vrp_submit_vrp_shipments'
require 'optimizer-client/models/post01_vrp_submit_vrp_subtours'
require 'optimizer-client/models/post01_vrp_submit_vrp_timewindows'
require 'optimizer-client/models/post01_vrp_submit_vrp_units'
require 'optimizer-client/models/post01_vrp_submit_vrp_vehicles'
require 'optimizer-client/models/post01_vrp_submit_vrp_zones'
require 'optimizer-client/models/status'
require 'optimizer-client/models/vrp_jobs_list'
require 'optimizer-client/models/vrp_result'
require 'optimizer-client/models/vrp_result_detail_quantities'
require 'optimizer-client/models/vrp_result_job'
require 'optimizer-client/models/vrp_result_job_graph_item'
require 'optimizer-client/models/vrp_result_solution'
require 'optimizer-client/models/vrp_result_solution_route'
require 'optimizer-client/models/vrp_result_solution_route_activities'
require 'optimizer-client/models/vrp_result_solution_route_activity_detail_timewindows'
require 'optimizer-client/models/vrp_result_solution_route_activity_details'

# APIs
require 'optimizer-client/api/vrp_api'

module OptimizerClient
  class << self
    # Customize default settings for the SDK using block.
    #   OptimizerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
